### ISSUE TITLE
질문이 있습니다.

### ISSUE THREAD

**Issue by PCloud63514** [zkdlu/first-street#1]
안녕하세요.
프로젝트를 참고하여 학습하던 중 질문사항이 있어 요청합니다.
루트 하위에 있는 applications 와 components는 인텔리제이 모듈로 디렉토리를 생성해야하나요?
또한 applications는 어떤 기준으로 생성해야하는지 간략히 설명해주실 수 있을까요?

**Comment by zkdlu** [comment]
> 루트 하위에 있는 applications 와 components는 인텔리제이 모듈로 디렉토리를 생성해야하나요?

어떻게 만들어주든 상관 없어요. 인텔리제이에서 모듈을 만들어 줄 때  applications/new-module 형태로 이름을 만들어주면 하위 디렉토리에 생기는데, 저는 디렉토리랑 gradle을 직접 작성 한 후 settings.gradle에 추가해주는 편이에요.

> 또한 applications는 어떤 기준으로 생성해야하는지 간략히 설명해주실 수 있을까요?

특별한 기준을 잡고 만들진 않았는데, 실행 될 수 있는 boot 앱을 만들어주고 component를 물리는 식으로 만들었습니다. 

proudct 컴포넌트를 물리면 product 앱이 되는것 처럼 msa 환경에 적합한 구조로 작업하려고 하고있습니다.
